name: nfl
channels:
  - conda-forge
dependencies:
  - pymc>=5
  - black
  - flake8
  - ipykernel
  - ipywidgets
  - isort
  - pre-commit
  - pyarrow
  - statsmodels
  - tqdm
  - pip
  - pip:
      - nflreadpy